Table users {
  id varchar(24) [primary key] 
  firstName varchar(255) [not null]
  lastName varchar(255) [not null]
  email varchar(255) [not null, unique]
  password varchar(255) [not null]
  phoneNumber varchar(20)
  country varchar(100)
}

Table products {
  id varchar(24) [primary key] 
  name varchar(255) [not null]
  description text [not null]
  price decimal(10,2) [not null]
  image varchar(255)
  owner varchar(24) [not null]
}

Ref: products.owner > users.id